channels:
  - bioconda
  - conda-forge
dependencies:
  - matplotlib=3.2.2
  - numpy=1.21.6
  - pyqt=5.12.3
  - python=3.7.0
  - python-javabridge=4.0.0
  - python-bioformats=4.0.5
  - scikit-image=0.19.3
  - tifffile=2021.7.2
